# Generated by Django 5.0.9 on 2024-10-05 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_total_likes_and_more'),
        ('recipes', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='images.image'),
        ),
    ]
