# Generated by Django 5.0.9 on 2024-10-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipe_total_likes_recipe_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
